account/urls.py
from django.urls import re_path
from . import views

app_name = 'account'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^(?P<store_account_id>[0-9]+)$', views.detail, name='detail'),
    re_path(r'^sign-in$', views.sign_in, name='sign-in'),
    re_path(r'^sign-up$', views.sign_up, name='sign-up'),
    re_path(r'^slave-signup$', views.slave_signup, name='slave_signup'),
    re_path(r'^sign_in_validate$', views.sign_in_validate, name='sign_in_validate'),
    re_path(r'^sign_up_validate$', views.sign_up_validate, name='sign_up_validate'),
    re_path(r'^logout$', views.logout, name='logout'),
]

inventory/urls.py
from django.urls import re_path
from . import views

app_name = 'inventory'


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^operation$', views.delete_update, name='operation'),
    re_path(r'^add-inventory$', views.add_inventory, name='add-inventory'),
    re_path(r'^update-inventory$', views.update_inventory, name='update-inventory'),
]

placeorder/urls.py
from django.urls import re_path
from . import views

app_name = 'placeorder'


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^add-selected-item$', views.add_selected_item, name='add_selected_item'),
    re_path(r'^operation$', views.delete_update, name='operation'),
    re_path(r'^operation-cart$', views.operation_cart, name='operation-cart'),
    re_path(r'^order-view$', views.order_view, name="order-view"),
    re_path(r'^order-delete$', views.order_delete, name="order-delete"),
    re_path(r'^order-item-list$', views.order_item_view, name="order-item-view"),
]

storeman/urls.py
from django.contrib import admin
from django.urls import re_path, include

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^account/', include('account.urls')),
    re_path(r'^welcome/', include('welcome.urls')),
    re_path(r'^inventory/', include('inventory.urls')),
    re_path(r'^placeorder/', include('placeorder.urls')),

]

welcome/urls.py
from django.urls import re_path
from . import views

app_name = 'welcome'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
]

placeorder/models.py
from django.db import models
# Create your models here.


# ToDO Order Table
class Order(models.Model):
    seller_id = models.PositiveSmallIntegerField()
    order_price = models.PositiveSmallIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.seller_id) + ' - ' + str(self.order_price)


# ToDO Order Item Table
class OrderItem(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    user_id = models.PositiveSmallIntegerField()
    order_item_name = models.CharField(max_length=90)
    order_item_qty = models.PositiveSmallIntegerField()
    order_item_price = models.PositiveSmallIntegerField()
    order_item_total = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.order_item_name + ' - ' + str(self.order_item_price)


# ToDO Current CartTable
class Cart(models.Model):
    cart_item_id = models.CharField(max_length=90)
    cart_item_name = models.CharField(max_length=90)
    cart_item_qty = models.PositiveSmallIntegerField()
    cart_item_price = models.PositiveSmallIntegerField()
    cart_item_total = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.cart_item_name + ' - ' + str(self.cart_item_price)

placeorder/views.py
from django.shortcuts import render
from .models import Order, OrderItem, Cart
from inventory.models import InventoryItems
# Create your views here.


def index(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})
    if 'user_id' not in request.session:
        return render(request, 'account/sign-in.html', context)
    all_items = InventoryItems.objects.filter(user_id=request.session['user_id'])
    # TODO RETURN VARIABLE
    all_carts = Cart.objects.all()
    if not all_carts:
        context.update({'all_items': all_items})
    else:
        billTotalValue = 0
        for item in all_carts:
            billTotalValue = billTotalValue + item.cart_item_total
            context.update({'all_items': all_items, 'all_carts': all_carts, 'billTotalValue': billTotalValue})
    return render(request, 'placeorder/index.html', context)


def add_selected_item(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})
    inventory_item = InventoryItems.objects.all()
    for item_contain in inventory_item:
        if item_contain.item_qty == 0:
            item_contain.delete()
    all_items = InventoryItems.objects.all()
    if int(request.POST['current-qty']) > 0:
        current_ordered_qty = int(request.POST['current-qty'])
        current_ordered_item_id = int(request.POST['order-item'])
        inventory_item = InventoryItems.objects.filter(pk=current_ordered_item_id)
        if inventory_item:
            for item_contain in inventory_item:
                item_id = item_contain.id
                item_name = item_contain.item_name
                item_price = item_contain.item_price
                item_qty = item_contain.item_qty
                all_carts = Cart.objects.filter(cart_item_id=item_id)
                if not all_carts:
                    availablitycheck = 0
                else:
                    availablitycheck = 1
                if availablitycheck == 1:
                    used_ordered_qty = 0
                    for cart_item in all_carts:
                        used_ordered_qty = used_ordered_qty + cart_item.cart_item_qty
                    item_qty = item_qty - used_ordered_qty
            if item_qty >= current_ordered_qty:
                new_cart = Cart()
                new_cart.cart_item_id = current_ordered_item_id
                new_cart.cart_item_name = item_name
                new_cart.cart_item_qty = int(current_ordered_qty)
                new_cart.cart_item_price = int(item_price)
                new_cart.cart_item_total = int(item_price * current_ordered_qty)
                new_cart.save()
            else:
                context.update({'successresponse': "Sufficient Item Not Available", 'max': int(item_qty)})
    else:
        context.update({'successresponse': "Invalid Request"})

    # TODO RETURN VARIABLE
    all_items = InventoryItems.objects.filter(user_id=request.session['user_id'])
    all_carts = Cart.objects.all()
    if not all_carts:
        context.update({'all_items': all_items})
    else:
        billTotalValue = 0
        for item in all_carts:
            billTotalValue = billTotalValue + item.cart_item_total
            context.update({'all_items': all_items, 'all_carts': all_carts, 'billTotalValue': billTotalValue})
    return render(request, 'placeorder/index.html', context)


def delete_update(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})
    # TODO Delete CART ITEM
    if 'delete' in request.POST:
        Cart.objects.filter(pk=request.POST['delete']).delete()
        context.update({'successresponse': 'Deleted Succesfully'})
    else:
        context.update({'successresponse': 'Invalid Request'})

    # TODO RETURN VARIABLE
    all_carts = Cart.objects.all()

    if not all_carts:
        all_items = InventoryItems.objects.filter(user_id=request.session['user_id'])
        context = context.update({'all_items': all_items})
    else:
        billTotalValue = 0
        for item in all_carts:
            billTotalValue = billTotalValue + item.cart_item_total
        all_items = InventoryItems.objects.filter(user_id=request.session['user_id'])
        context.update({'all_items': all_items, 'all_carts': all_carts, 'billTotalValue': billTotalValue})
    return render(request, 'placeorder/index.html', context)


def operation_cart(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})

    # TODO DELETE CART
    if 'delete' in request.POST:
        Cart.objects.all().delete()
        context.update({'successresponse': 'Deleted Cart Succesfully'})
    # TODO GENERATE BILL
    elif 'generate' in request.POST:
            all_carts = Cart.objects.all()
            if not all_carts:
                context.update({'successresponse': 'add items to cart'})
            else:
                user_id = request.session['user_id']
                new_order = Order()
                new_order.seller_id = user_id
                billTotalValue = 0
                for item in all_carts:
                    billTotalValue = billTotalValue + item.cart_item_total
                new_order.order_price = billTotalValue
                new_order.save()
                for item in all_carts:
                    order_item_total = int(item.cart_item_price) * int(item.cart_item_qty)
                    new_orderitem = OrderItem.objects.create(order_id=new_order, user_id=user_id,
                                                             order_item_name=item.cart_item_name,
                                                             order_item_qty=item.cart_item_qty,
                                                             order_item_price=item.cart_item_price,
                                                             order_item_total=order_item_total)

                    inventoryitem = InventoryItems.objects.filter(id=item.cart_item_id)
                    for inventory_contain in inventoryitem:
                        inventory_contain.item_qty = inventory_contain.item_qty - item.cart_item_qty
                        inventory_contain.save()
                    new_orderitem.save()
                Cart.objects.all().delete()
                context.update({'successresponse': 'Bill Generated Successful'})
    # TODO END OF GENERATE BILL
    else:
        context.update({'successresponse': 'Invalid Request'})

    # TODO RETURN VARIABLE
    all_carts = Cart.objects.all()
    if not all_carts:
        all_items = InventoryItems.objects.filter(user_id=request.session['user_id'])
        context.update({'all_items': all_items})
    else:
        billTotalValue = 0
        for item in all_carts:
            billTotalValue = billTotalValue + item.cart_item_total
        all_items = InventoryItems.objects.filter(user_id=request.session['user_id'])
        context.update({'all_items': all_items, 'all_carts': all_carts, 'billTotalValue': billTotalValue})
    return render(request, 'placeorder/index.html', context)


def order_view(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})
    user_id = request.session['user_id']
    orders = Order.objects.filter(seller_id=user_id)
    if orders:
        context.update({'orders': orders})
    return render(request, 'placeorder/orderlist.html', context)


def order_delete(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})
    if 'delete' in request.POST:
        Order.objects.filter(pk=request.POST['delete']).delete()
        OrderItem.objects.filter(order_id=request.POST['delete']).delete()
        context.update({'successresponse': 'Deleted Order'})
    elif 'order_id' in request.POST:
        if 'order_id' in request.POST:
            order_id = request.POST['order_id']
            order_item = OrderItem.objects.filter(order_id=order_id)
        if order_item:
            context.update({'order_item': order_item})
        return render(request, 'placeorder/orderitemlist.html', context)

    user_id = request.session['user_id']
    orders = Order.objects.filter(seller_id=user_id)
    if orders:
        context.update({'orders': orders})
    return render(request, 'placeorder/orderlist.html', context)


def order_item_view(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})
    user_id = request.session['user_id']
    order_item = OrderItem.objects.filter(user_id=user_id)
    if order_item:
        context.update({'order_item': order_item})
    return render(request, 'placeorder/orderitemlist.html', context)

placeorder/templates/placeorder/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StoreMan</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style type="text/css" rel="stylesheet">
    .sman-sidebar{
        padding-right: 25px;
    }
    .sman-sidebar-header{
        text-align: center;
        background-color: #13a1a5 !important;
        color: white;
        font-size: 18px;
        font-weight: 600;
    }
    .sman-sidebar{
        border-right: 150px solid white;
        background-color: #13a1a5 !important;
        height: 800px;
    }
    .sman-sidebar-item{
        background-color: white !important;
        margin-bottom: 40px;
        font-size: 18px;
        font-weight: 600;
        color: #13a1a5;
        padding-right: 15px;
    }
    .sman-sidebar-content{
        margin-top: 100px;
    }
    a{
        text-decoration: none;
        color: inherit;
    }
    </style>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand color1" href="{% url 'welcome:index' %}">StoreMan</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="color1" href="{% url 'welcome:index' %}">HOME</a></li>
                        <li><a class="color1" href="#tour">ABOUT US</a></li>
                        <li><a class="color1" href="#contact">CONTACT</a></li>
                        {% block navblock %}
                        {% endblock %}
                    </ul>
                </div>
            </div>
        </nav>


    <!-- ########################################   BODY-START #############################################-->
<div class="container-fluid sman-body-margin">
    <div class="row">
        <div class="col-md-3 text-right sman-sidebar">
            <div class="sman-sidebar-header">
                Administrate
            </div>
            <div class="sman-sidebar-content">
                <div class="sman-sidebar-item">
                    <a href="{% url 'inventory:index' %}">Inventorty Items</a>
                </div>
                <div class="sman-sidebar-item">
                    <a href="{%url 'inventory:add-inventory' %}">Add Inventorty Item</a>
                </div>
                <div class="sman-sidebar-item">
                    <a href="{% url 'placeorder:index' %}">Generate Bill</a>
                </div>
                <div class="sman-sidebar-item">
                    <a href="{% url 'placeorder:order-view' %}">Orders</a>
                </div>
                <div class="sman-sidebar-item">
                    <a href="{% url 'placeorder:order-item-view' %}">Order Items</a>
                </div>
                {% if admin_type %}
                {% block sideblock %}
                {% endblock %}
                {% endif %}
            </div>
        </div>
    {% block body %}
    {% endblock %}
</div>
</div>
    <!-- ########################################   BODY-END #############################################-->


    <div class="sman-footer-main">
        <div class="float-left color1 font-glyphy"><span class="fa fa-google-plus-square color1"></span><span class="fa fa-facebook-square color1"></span><span class="fa fa-instagram color1"></span><span class="fa fa-twitter-square color1"></span></div>
        <div class="footer-copyright float-right color1">© 2018 Copyright:
            <a href="#" class="color1"> StoreMan.com</a>
        </div>
    </div>
</body>
</html>

placeorder/templates/placeorder/index.html
{% extends 'placeorder/base.html' %}
{% block navblock %}
<li><a class="color1" href="{% url 'account:logout' %}">LOGOUT</a></li>
{% endblock %}
{% block sideblock%}
<div class="sman-sidebar-item">
    <a href="{% url 'account:slave_signup' %}">Add User</a>
</div>
{% endblock %}
{% block body %}
<!-- loads the path to your static files -->
<style type="text/css" rel="stylesheet">
    .color1{
        font-weight: 600;
        color: #13a1a5 !important;
    }
    .color1-bg{
        background-color: #13a1a5 !important;
        border-radius: 15px;
    }
    .btn-outline-primary{
        border-color: #13a1a5;
        border-style: solid;
        border-width: 5px;
    }
    .sman-footer-main{
        position: fixed;
        bottom: 0px;
        height: 30px;
        display: inline;
        width: 100%;
        color: #13a1a5;
        padding-right: 30px;
        padding-left: 30px;
        background-color: white;
    }
    .float-left{
        float: left;
    }
    .float-right{
        float: right;
    }
    text-center{
        text-align: center;
    }
    inline-block{
        display: inline;
    }

    .sman-btn{
        background-color: white;
        border-style: solid;
        border-radius: 5px;
        border-color: #13a1a5;
        color: #13a1a5;
        padding-top: 7px;
        padding-bottom: 7px;
        padding-left: 15px;
        padding-right: 15px;
        min-width: 150px;
        font-weight: 600;
        font-size: 15px;
    }
    .sman-btn-main
    {
        margin-top: 100px;
    }
    .sman-content-main{
        padding-bottom: 10px;
        padding-top: 10px;
        font-weight: 600;
        font-size: 15px;
        margin-top: 100px;
        background-color: white;
        color:#13a1a5;

    }
    .sman-body-margin{
        margin-top: 100px;
        margin-bottom: 100px;
    }
    .font-weight-list
    {
        font-weight: 600 !important;
    }
    .font-glyphy
    {
        font-size: 20px;
    }
    .fa{
        margin-left: 40px;
    }
    .footer-copyright{
        padding-top: 10px;
    }
    @media only screen and (max-width: 600px) {
        .sman-body{
            padding: 0 !important;
        }
    }
    .color-white{
        color: white;
    }
    .sman-form-header{
        font-weight: 600;
        font-size: 20px;
        width: 100%;
        background-color: #13a1a5 !important;
    }
    .sman-row{
        padding: 0;
    }
    .sman-container{
        padding: 0;
        background-color: black;
    }
    .sman-inline{
        display: inline-block;
    }
    .sman-inventory-content{
        margin-top: 100px;
    }
    .table_item
    {
        padding-right: 50px;
        margin-bottom:20px;
    }
    td{
        text-align: left;
    }


    .table-update-btn, .table-delete-btn{

        width: 30px;
        height: 30px;
        border: 0;
        margin-top: -25px;
        background-color: Transparent;
        color: #13a1a5;
    }

    .table-add-btn{
        margin-top: -15px !important;
        width: 130px;
        height: 30px;
        border: 0;
        background-color: Transparent;
        font-weight: 600;
    }


    .sman-select-item, .sman-item-current-qty{
        background-color: white;
        border-style: solid;
        border-radius: 5px;
        border-color: #13a1a5;
        color: #13a1a5;
        padding-top: 7px;
        padding-bottom: 7px;
        padding-left: 15px;
        padding-right: 15px;
        min-width: 150px;
        font-weight: 600;
        font-size: 15px;
        border-width: 2px;
        margin-right: 15px;
    }
    .sman-item-current-qty{
        min-width: 80px !important;
        max-width: 100px !important;
    }
    .color-primary{
        color: #13a1a5 !important;
    }

    .color-primary-bg{
        background-color: #13a1a5 !important;
    }
    .sManBillTotal{
    background-color: white;
    color: #13a1a5 !important;
    font-size: 18px;
    font-weight: 600;
    padding-top: 5px
    }
    td{
        padding-top: 15px;
        border-bottom: solid #13a1a5;
    }
    .sMan-float-left{
        float: left;
    }
    .sMan-float-right{
        float: right;
    }
    .sMan-billDetailHeader{
        padding-top: 5px;
        padding-bottom: 5px;
        padding-right:  20px;
        padding-left: 20px;
        overflow: hidden;
        font-weight: 600;
        font-size: 18px;

    }
    .billDetailsHeaderRow{
        border-bottom: solid #13a1a5;
        border-right: solid #13a1a5;
        border-left: solid #13a1a5;
    }
    th{
        color: #13a1a5;
    }
    .billTableForm{
        margin-top: 20px;
    }
    th, td{
        padding: 10px 10px 10px 10px;
    }
    .sMan_Warning{
        color: red;
        font-weight: 600;
        font-size: 16px;
    }

</style>
{% load staticfiles %}
<div class="col-md-9 text-center">
            <div class="row">
                <div class="sman-form-header">
                    <font class="color-white">Billing</font>
                </div>
                <div class="sman-inventory-content">
                    <div class="sman-form-header">
                        <font class="color-white">Add Item</font>
                    </div>
                    <hr>
                    {% if all_items %}
                    <form action="{% url 'placeorder:add_selected_item' %}" method="post">
                        {% csrf_token %}

                        <select class="sman-select-item" name="order-item">
                            {% for item in all_items %}
                            <option value="{{ item.id }}">{{ item.item_name }}</option>
                            {% endfor %}
                        </select>
                        <input type="number" step="0" class="sman-item-current-qty" name="current-qty" value="0"/>
                        <button class="table-add-btn sman-inline color1-bg color-white" type="submit" id="add-item-btn"><span class="glyphicon glyphicon-plus-sign "></span>&nbsp; &nbsp; Add Item</button>
                    </form>
                        <hr>
                    <div class="sMan-billDetailHeader color-primary-bg color-white">
                        <label class="current_order_id sMan-float-left">OrderID</label>
                        <lable clas="orderDetailHeaderLabel">Order Details</lable>
                        <label class="seller_name sMan-float-right">SellerName</label>
                    </div>
                    <div>
                        {% if successresponse %} <span class="sMan_Warning">{{ successresponse }} </span>{% if max %} <span class="sMan_Warning">[Only {{ max }}] Available </span>{% endif %}{% else %} <br> {% endif %}

                    </div>
                    <div class="billTableForm">
                        <form action="{% url 'placeorder:operation' %}" method="post">
                            {% csrf_token %}
                            <table align="center" class="billTable">
                                <tr class="billDetailsHeaderRow">
                                    <th>Item Name</th>
                                    <th>Item Price</th>
                                    <th>Item Quantity</th>
                                    <th>Price</th>
                                    <th></th>
                                </tr>
                                {% if all_carts %}
                                {% for item in all_carts %}
                                <tr>
                                    <td><label class="table_item">{{ item.cart_item_name }}</label></td>
                                    <td><label class="table_item">{{ item.cart_item_price }}</label></td>
                                    <td><label class="table_item">{{ item.cart_item_qty }}</label></td>
                                    <td><label class="table_item">{{ item.cart_item_total }}</label></td>
                                    <td class="table_item">
                                        <button class="table-delete-btn" type="submit" id="item_update{{ forloop.counter }}" name="delete" value="{{ item.id }}"><span class="glyphicon glyphicon-trash"/></button>
                                    </td>
                                </tr>
                                {% endfor %}
                                {% else %}
                                <tr><td colspan="6">Cart is empty</td></tr>
                                {% endif %}
                            </table>
                        </form>
                    </div>
                    <form action="{% url 'placeorder:operation-cart' %}" method="post">
                        {% csrf_token %}
                        <div class="sManBillTotal color-primary"><label class="sManBillTotalLabelName">Total : </label>&nbsp;&nbsp;&nbsp;<labe class="sManBillTotalLabelValue" name="totalValue">{% if billTotalValue %} {{ billTotalValue }} {% else %} 0 {% endif %}</labe></div>
                        <br><button class="table-add-btn sman-inline color1-bg color-white" type="submit" name="generate" value="1"><span class="glyphicon glyphicon-shopping-cart "></span>&nbsp; &nbsp; Generate Bill</button>
                        &nbsp;&nbsp;
                        <button class="table-add-btn sman-inline color1-bg color-white" type="submit" name="delete" value="1"><span class="glyphicon glyphicon-trash"></span>&nbsp; &nbsp; Clear Cart </button>
                    </form>
                    {% else %}
                    <h2>You don't have any items</h2>
                    {% endif %}
                    <hr>
                </div>

            </div>
        </div>
{% endblock %}