account/urls.py
from django.urls import re_path
from . import views

app_name = 'account'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^(?P<store_account_id>[0-9]+)$', views.detail, name='detail'),
    re_path(r'^sign-in$', views.sign_in, name='sign-in'),
    re_path(r'^sign-up$', views.sign_up, name='sign-up'),
    re_path(r'^slave-signup$', views.slave_signup, name='slave_signup'),
    re_path(r'^sign_in_validate$', views.sign_in_validate, name='sign_in_validate'),
    re_path(r'^sign_up_validate$', views.sign_up_validate, name='sign_up_validate'),
    re_path(r'^logout$', views.logout, name='logout'),
]

storeman/urls.py
from django.contrib import admin
from django.urls import re_path, include

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^account/', include('account.urls')),
    re_path(r'^welcome/', include('welcome.urls')),
    re_path(r'^inventory/', include('inventory.urls')),
    re_path(r'^placeorder/', include('placeorder.urls')),

]

welcome/urls.py
from django.urls import re_path
from . import views

app_name = 'welcome'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
]

welcome/models.py
from django.db import models

# Create your models here.

welcome/views.py
from django.shortcuts import render
from inventory.views import index as welcome
# Create your views here.


def index(request):
    if 'user_id' in request.session:
        return welcome(request)
    else:
        context = {}
        return render(request, 'welcome/index.html', context)

welcome/templates/welcome/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StoreMan</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand color1" href="{% url 'welcome:index' %}">StoreMan</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="color1" href="{% url 'welcome:index' %}">HOME</a></li>
                        <li><a class="color1" href="#tour">ABOUT US</a></li>
                        <li><a class="color1" href="#contact">CONTACT</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle color1" data-toggle="dropdown" href="#">MORE
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="color1" href="{% url 'account:sign-in' %}"><b>SIGN-IN</b></a></li>
                                <li><a class="color1" href="{% url 'account:sign-up' %}"><b>SIGN-UP</b></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    {% block body %}
    {% endblock %}

    <div class="sman-footer-main">
        <div class="float-left color1 font-glyphy"><span class="fa fa-google-plus-square color1"></span><span class="fa fa-facebook-square color1"></span><span class="fa fa-instagram color1"></span><span class="fa fa-twitter-square color1"></span></div>
        <div class="footer-copyright float-right color1">© 2018 Copyright:
            <a href="#" class="color1"> StoreMan.com</a>
        </div>
    </div>
</body>
</html>

welcome/templates/welcome/index.html
{% extends 'welcome/base.html' %}
{% block body %}
<!-- loads the path to your static files -->
{% load staticfiles %}
<style type="text/css" rel="stylesheet">


            .color1{
                font-weight: 600;
                color: #13a1a5 !important;
            }

            .sman-body{
                margin-top: 150px;
                margin-bottom: 100px;
                padding-left: 500px;
                padding-right: 500px;
                width: 100%;
            }

            .sman-body-content{
                color: white;
            }
            .bgimage{
                background: url("{% static 'welcome/images/imagebg.jpg' %}") no-repeat;
                background-size: cover;
                height: 400px;
                border-radius: 25px;

            }
            .btn-outline-primary{
                border-color: #13a1a5;
                border-style: solid;
                border-width: 5px;
            }


            .sman-footer-main{
                position: fixed;
                bottom: 0px;
                height: 30px;
                display: inline;
                width: 100%;
                color: #13a1a5;
                padding-right: 30px;
                padding-left: 30px;
                background-color: white;
            }
            .float-left{
                float: left;
            }
            .float-right{
                float: right;
            }
            text-center{
                text-align: center;
            }
            inline-block{
                display: inline;
            }
            .sman-btn{
                background-color: white;
                border-style: solid;
                border-radius: 5px;
                border-color: #13a1a5;
                color: #13a1a5;
                padding-top: 7px;
                padding-bottom: 7px;
                padding-left: 15px;
                padding-right: 15px;
                min-width: 150px;
                font-weight: 600;
                font-size: 15px;
            }
            .sman-btn-main
            {
                margin-top: 100px;
            }
            .sman-content-main{
                padding-bottom: 10px;
                padding-top: 10px;
                font-weight: 600;
                font-size: 15px;
                margin-top: 100px;
                background-color: white;
                color:#13a1a5;

            }
            .font-weight-list
            {
                font-weight: 600 !important;
            }
            .font-glyphy
            {
                font-size: 20px;
            }
            .fa{
                margin-left: 40px;
            }
            .footer-copyright{
                padding-top: 10px;
            }
            @media only screen and (max-width: 600px) {
                .sman-body{
                    padding: 0 !important;
                }
            }
        </style>
<!-- ########################################   BODY-START #############################################-->
<div class="container-fluid">
    <div class="row">
        <div class="sman-body text-center inline-block">
            <div class=" bgimage">
                <div class="sman-body-content">
                    <div class="container-fluid">
                        <div class="row sman-content-main">
                            <div class="col-sm-12">
                                <h3 class="font-weight-list">Welcome</h3>
                                The purpose of business is to create and keep a customer.
                                <br>Take the first step...
                            </div>
                        </div>
                        <div class="row sman-btn-main">
                            <div class="col-md-6"><button type="button" class="btn sman-btn" onclick="location.href='{% url 'account:sign-in' %}'">Sign-In</button></div>
                            <div class="col-md-6"><button type="button" class="btn sman-btn" onclick="location.href='{% url 'account:sign-up' %}'">Sign-Up</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ########################################   BODY-END #############################################-->
{% endblock %}