account/urls.py
from django.urls import re_path
from . import views

app_name = 'account'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^(?P<store_account_id>[0-9]+)$', views.detail, name='detail'),
    re_path(r'^sign-in$', views.sign_in, name='sign-in'),
    re_path(r'^sign-up$', views.sign_up, name='sign-up'),
    re_path(r'^slave-signup$', views.slave_signup, name='slave_signup'),
    re_path(r'^sign_in_validate$', views.sign_in_validate, name='sign_in_validate'),
    re_path(r'^sign_up_validate$', views.sign_up_validate, name='sign_up_validate'),
    re_path(r'^logout$', views.logout, name='logout'),
]

inventory/urls.py
from django.urls import re_path
from . import views

app_name = 'inventory'


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^operation$', views.delete_update, name='operation'),
    re_path(r'^add-inventory$', views.add_inventory, name='add-inventory'),
    re_path(r'^update-inventory$', views.update_inventory, name='update-inventory'),
]

placeorder/urls.py
from django.urls import re_path
from . import views

app_name = 'placeorder'


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^add-selected-item$', views.add_selected_item, name='add_selected_item'),
    re_path(r'^operation$', views.delete_update, name='operation'),
    re_path(r'^operation-cart$', views.operation_cart, name='operation-cart'),
    re_path(r'^order-view$', views.order_view, name="order-view"),
    re_path(r'^order-delete$', views.order_delete, name="order-delete"),
    re_path(r'^order-item-list$', views.order_item_view, name="order-item-view"),
]

storeman/urls.py
from django.contrib import admin
from django.urls import re_path, include

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^account/', include('account.urls')),
    re_path(r'^welcome/', include('welcome.urls')),
    re_path(r'^inventory/', include('inventory.urls')),
    re_path(r'^placeorder/', include('placeorder.urls')),

]

welcome/urls.py
from django.urls import re_path
from . import views

app_name = 'welcome'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
]

inventory/models.py
from django.db import models
from account.models import StoreAccount

# Create your models here.

# ToDo  StoreAccount Table


class InventoryItems(models.Model):
    user_id = models.ForeignKey(StoreAccount, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=90)
    item_qty = models.PositiveSmallIntegerField()
    item_price = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.item_name + ' - ' + str(self.item_qty)

inventory/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import InventoryItems, StoreAccount
from placeorder.views import index as generate_bill_view

# Create your views here.


def index(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})
    else:
        context.update({'admin_slave': 'slave'})
    if 'successresponse' in request.GET:
        successresponse = request.GET['successresponse']
        context.update({'successresponse': successresponse})
    if 'user_id' not in request.session:
        return render(request, 'account/sign-in.html', context)
    user_id = request.session['user_id']
    all_items = InventoryItems.objects.all()
    for item_contain in all_items:
        if item_contain.item_qty == 0:
            item_contain.delete()
    all_items = InventoryItems.objects.filter(user_id=user_id)
    context.update({'all_items': all_items, 'user_id': user_id})
    return render(request, 'inventory/index.html', context)


def delete_update(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})
    if 'delete' in request.POST:
        InventoryItems.objects.filter(pk=request.POST['delete']).delete()
        return index(request)
    elif 'update' in request.POST:
        item = InventoryItems.objects.filter(pk=request.POST['update'])
        for item_contain in item:
            item_name= item_contain.item_name
            item_price= item_contain.item_price
            item_qty= item_contain.item_qty
        context = {
            'item_name': item_name,
            'item_price': item_price,
            'item_qty': item_qty,
            'item_id': request.POST['update']
        }
        return render(request, 'inventory/update.html', context)
    elif 'add' in request.POST:
        user_id = request.session['user_id']

        user = StoreAccount.objects.get(pk=user_id)
        item_qty = request.POST['item_qty']
        item_price = request.POST['item_price']
        item_name = request.POST['item_name']
        new_inventory_item = InventoryItems.objects.create(user_id=user, item_name=item_name, item_qty=item_qty, item_price=item_price)
        new_inventory_item.save()
        context.update({'successresponse': 'inventory item added'})
        return render(request, 'inventory/add-inventory.html', context)
    else:
        return index(request)


def update_inventory(request):
    successresponse = ""
    if 'update' in request.POST:
        item_id = request.POST['item_id']
        item_name = request.POST['item_name']
        item_qty = request.POST['item_qty']
        item_price = request.POST['item_price']
        inventory_obj = InventoryItems.objects.filter(pk=item_id)
        for inventory_item in inventory_obj:
            inventory_item.item_name = item_name
            inventory_item.item_qty = item_qty
            inventory_item.item_price = item_price
            inventory_item.save()
        successresponse = "update successfully"
    else:
        successresponse = "Error Update Failed"
    return HttpResponseRedirect('/inventory/?successresponse='+successresponse)


def add_inventory(request):
    context = {}
    if 'admin_type' not in request.session:
        return render(request, 'account/sign-in.html', context)
    admin_type = request.session['admin_type']
    if admin_type == 1:
        context.update({'admin_type': admin_type})
    return render(request, 'inventory/add-inventory.html', context)

inventory/templates/inventory/add-inventory.html
<style  type="text/css" rel="stylesheet">
    .color1{
        font-weight: 600;
        color: #13a1a5 !important;
    }

    .sman-footer-main{
        position: fixed;
        bottom: 0px;
        height: 30px;
        display: inline;
        width: 100%;
        color: #13a1a5;
        padding-right: 30px;
        padding-left: 30px;
        background-color: white;
    }
    .float-left{
        float: left;
    }
    .float-right{
        float: right;
    }
    text-center{
        text-align: center;
    }
    inline-block{
        display: inline;
    }

    /*  Button Style */

    .btn-outline-primary{
        border-color: #13a1a5;
        border-style: solid;
        border-width: 5px;
    }
    .sman-btn{
        background-color: white;
        border-style: solid;
        border-radius: 5px;
        border-color: #13a1a5;
        color: #13a1a5;
        padding-top: 7px;
        padding-bottom: 7px;
        padding-left: 15px;
        padding-right: 15px;
        min-width: 150px;
        font-weight: 600;
        font-size: 15px;
    }
    .sman-input-login
    {
        margin-right: 50px;
        color: #13a1a5;
        font-weight: 600;
        border-style: solid;
        border-radius: 2px;
        min-height: 30px;
        min-width: 200px;
        border-color: #13a1a5;

    }
    .sman-btn-main
    {
        margin-top: 100px;
    }

    .sman-content-main{
        padding-bottom: 10px;
        padding-top: 10px;
        font-weight: 600;
        font-size: 15px;
        margin-top: 100px;
        background-color: white;
        color:#13a1a5;

    }
    .sman-body-margin{
        margin-top: 100px;
        margin-bottom: 100px;
    }
    .font-weight-list
    {
        font-weight: 600 !important;
    }
    .font-glyphy
    {
        font-size: 20px;
    }
    .fa{
        margin-left: 40px;
    }
    .footer-copyright{
        padding-top: 10px;
    }
    @media only screen and (max-width: 600px) {
        .sman-body{
            padding: 0 !important;
        }
    }
    .color-white{
        color: white;
    }
    .sman-form-header{
        font-weight: 600;
        font-size: 20px;
        width: 100%;
        background-color: #13a1a5 !important;
    }
    .sman-login-context{
        margin-top: 100px;
        margin-bottom: 100px;

    }
    .sman-row{
        padding: 0;
    }
    .sman-container{
        padding: 0;
        background-color: black;
    }
    div.sman-inline{
        display: inline-block;
    }
    .sman-align-left{
        text-align: left;
    }
    .sman-align-center{
        text-align: center;
    }
    .sman-btn-container{
        margin-top: 20px;
    }
    .sman-radio-label{
        margin-right: 50px;
        color: #13a1a5;
        font-weight: 600;
        font-size: 15px;
    }
    .sman-color-warning{
        color: red;
    }
    .table-item{
        padding-right: 20px;
        margin-bottom: 20px;
    }
</style>
{% extends 'inventory/base.html' %}
{% block navblock %}
<li><a class="color1" href="{% url 'account:logout' %}">LOGOUT</a></li>
{% endblock %}
{% block sideblock%}
<div class="sman-sidebar-item">
    <a href="{% url 'account:slave_signup' %}">Add User</a>
</div>
{% endblock %}
{% block body %}
<div class="col-md-9 text-center">
            <div class="row">
                <div class="sman-form-header">
                    <font class="color-white">Add Inventory Item</font>
                </div>
                <div class="sman-login-context">
                    <div class="sman-inline sman-align-left">
                        <br>
                        <hr>
                        <table>
                        <form method="post" action="{%url 'inventory:operation' %}">
                            {% csrf_token %}
                            <tr>
                                <td><label class="table-item sman-color-warning">ADD</label></td>
                                <td><label class="table-item">Item Name</label></td>
                                <td><label class="table-item sman-color-warning">:</label></td>
                                <td><input class="table-item sman-input-login" type="text" name="item_name" placeholder="Enter Item Name"></td>
                            </tr>
                            <tr>
                                <td><label class="table-item sman-color-warning">ADD</label></td>
                                <td><label class="table-item">Item Qyantity</label></td>
                                <td><label class="table-item sman-color-warning">:</label></td>
                                <td><input class="table-item sman-input-login" type="text" name="item_qty" placeholder="Enter Quantity"></td>
                            </tr>
                            <tr>
                                <td><label class="table-item sman-color-warning">ADD</label></td>
                                <td><label class="table-item">Item Price</label></td>
                                <td><label class="table-item sman-color-warning">:</label></td>
                                <td><input class="table-item sman-input-login" type="text" name="item_price" placeholder="Enter Price"></td>
                            </tr>
                            <tr>
                                <td colspan="4">
                                    <div class="sman-align-center sman-btn-container">
                                        <input class="sman-btn btn-outline-primary" type="Submit" value="Add" name="add"/>
                                    </div>
                                </td>
                            </tr>
                        </form>
                        </table>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

inventory/templates/inventory/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StoreMan</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style type="text/css" rel="stylesheet">
    .sman-sidebar{
        padding-right: 25px;
    }
    .sman-sidebar-header{
        text-align: center;
        background-color: #13a1a5 !important;
        color: white;
        font-size: 18px;
        font-weight: 600;
    }
    .sman-sidebar{
        border-right: 150px solid white;
        background-color: #13a1a5 !important;
        height: 800px;
    }
    .sman-sidebar-item{
        background-color: white !important;
        margin-bottom: 40px;
        font-size: 18px;
        font-weight: 600;
        color: #13a1a5;
        padding-right: 15px;
    }
    .sman-sidebar-content{
        margin-top: 100px;
    }
    a{
        text-decoration: none;
        color: inherit;
    }
    </style>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand color1" href="{% url 'welcome:index' %}">StoreMan</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="color1" href="{% url 'welcome:index' %}">HOME</a></li>
                        <li><a class="color1" href="#tour">ABOUT US</a></li>
                        <li><a class="color1" href="#contact">CONTACT</a></li>
                        {% block navblock %}
                        {% endblock %}
                    </ul>
                </div>
            </div>
        </nav>


    <!-- ########################################   BODY-START #############################################-->
<div class="container-fluid sman-body-margin">
    <div class="row">
        <div class="col-md-3 text-right sman-sidebar">
            <div class="sman-sidebar-header">
                Administrate
            </div>
            <div class="sman-sidebar-content">
                <div class="sman-sidebar-item">
                    <a href="{% url 'inventory:index' %}">Inventorty Items</a>
                </div>
                <div class="sman-sidebar-item">
                    <a href="{%url 'inventory:add-inventory' %}">Add Inventorty Item</a>
                </div>
                <div class="sman-sidebar-item">
                    <a href="{% url 'placeorder:index' %}">Generate Bill</a>
                </div>
                <div class="sman-sidebar-item">
                    <a href="{% url 'placeorder:order-view' %}">Orders</a>
                </div>
                <div class="sman-sidebar-item">
                    <a href="{% url 'placeorder:order-item-view' %}">Order Items</a>
                </div>
                {% if admin_type %}
                {% block sideblock %}
                {% endblock %}
                {% endif %}

            </div>
        </div>
    {% block body %}
    {% endblock %}
</div>
</div>
    <!-- ########################################   BODY-END #############################################-->


    <div class="sman-footer-main">
        <div class="float-left color1 font-glyphy"><span class="fa fa-google-plus-square color1"></span><span class="fa fa-facebook-square color1"></span><span class="fa fa-instagram color1"></span><span class="fa fa-twitter-square color1"></span></div>
        <div class="footer-copyright float-right color1">© 2018 Copyright:
            <a href="#" class="color1"> StoreMan.com</a>
        </div>
    </div>
</body>
</html>

inventory/templates/inventory/index.html
{% extends 'inventory/base.html' %}

{% block navblock %}
<li><a class="color1" href="{% url 'account:logout' %}">LOGOUT</a></li>
{% endblock %}
{% block sideblock%}
<div class="sman-sidebar-item">
    <a href="{% url 'account:slave_signup' %}">Add User</a>
</div>
{% endblock %}
{% block body %}
<!-- loads the path to your static files -->
{% load staticfiles %}
<style type="text/css" rel="stylesheet">
    .color1{
        font-weight: 600;
        color: #13a1a5 !important;
    }
    .btn-outline-primary{
        border-color: #13a1a5;
        border-style: solid;
        border-width: 5px;
    }
    .sman-footer-main{
        position: fixed;
        bottom: 0px;
        height: 30px;
        display: inline;
        width: 100%;
        color: #13a1a5;
        padding-right: 30px;
        padding-left: 30px;
        background-color: white;
    }
    .float-left{
        float: left;
    }
    .float-right{
        float: right;
    }
    text-center{
        text-align: center;
    }
    inline-block{
        display: inline;
    }

    .sman-btn{
        background-color: white;
        border-style: solid;
        border-radius: 5px;
        border-color: #13a1a5;
        color: #13a1a5;
        padding-top: 7px;
        padding-bottom: 7px;
        padding-left: 15px;
        padding-right: 15px;
        min-width: 150px;
        font-weight: 600;
        font-size: 15px;
    }
    .sman-btn-main
    {
        margin-top: 100px;
    }
    .sman-content-main{
        padding-bottom: 10px;
        padding-top: 10px;
        font-weight: 600;
        font-size: 15px;
        margin-top: 100px;
        background-color: white;
        color:#13a1a5;

    }
    .sman-body-margin{
        margin-top: 100px;
        margin-bottom: 100px;
    }
    .font-weight-list
    {
        font-weight: 600 !important;
    }
    .font-glyphy
    {
        font-size: 20px;
    }
    .fa{
        margin-left: 40px;
    }
    .footer-copyright{
        padding-top: 10px;
    }
    @media only screen and (max-width: 600px) {
        .sman-body{
            padding: 0 !important;
        }
    }
    .color-white{
        color: white;
    }
    .sman-form-header{
        font-weight: 600;
        font-size: 20px;
        width: 100%;
        background-color: #13a1a5 !important;
    }
    .sman-row{
        padding: 0;
    }
    .sman-container{
        padding: 0;
        background-color: black;
    }
    div.sman-inline{
        display: inline-block;
    }
    .sman-inventory-content{
        margin-top: 100px;
    }
    td, th{
        padding: 10px 10px 10px 10px;
    }
    .billDetailsHeaderRow{
        border-bottom: solid #13a1a5;
        border-right: solid #13a1a5;
        border-left: solid #13a1a5;
    }
    th{
        color: #13a1a5;
    }
    td{
        text-align: left;
    }

    .table-update-btn, .table-delete-btn{

        width: 30px;
        height: 30px;
        border: 0;
        margin-bottom: 5px;
        background-color: Transparent;
        color: #13a1a5;
    }
    .sMan_Warning{
        color: red;
        font-weight: 600;
        font-size: 16px;
    }

</style>
<div class="col-md-9 text-center">
            <div class="row">
                <div class="sman-form-header">
                    <font class="color-white">Manage Inventory</font>
                </div>
                <div class="sman-inventory-content">
                    <hr>
                    {% if all_items %}
                    <form action="{% url 'inventory:operation' %}" method="post">
                        {% csrf_token %}
                        <hr>
                        <div class="sMan-billDetailHeader color-primary-bg color-white">
                            <label class="current_order_id sMan-float-left">OrderID</label>
                            <lable clas="orderDetailHeaderLabel">Order Details</lable>
                            <label class="seller_name sMan-float-right">SellerName</label>
                        </div>
                        <div>
                            {% if successresponse %} <span class="sMan_Warning">{{ successresponse }} </span>{% else %} <br> {% endif %}
                        </div>
                        <table align="center">
                            <tr class="billDetailsHeaderRow">
                                <th>Item Name</th>
                                <th>Item Quantity</th>
                                <th>Item Price</th>
                                <th></th>
                                <th></th>
                            </tr>
                            {% for item in all_items %}
                            <tr>
                                <td><label class="table_item">{{ item.item_name }}</label></td>
                                <td><label class="table_item">{{ item.item_qty }}</label></td>
                                <td><label class="table_item">{{ item.item_price }}</label></td>
                                <td class="table_item">{% if admin_slave %}{% else %}<button class="table-delete-btn" type="submit" id="item_update{{ forloop.counter }}" name="delete" value="{{ item.id }}"><span class="glyphicon glyphicon-trash"/></button>{% endif %}</td>
                                <td class="table_item">{% if admin_slave %}{% else %}<button class="table-update-btn" type="submit" id="item_delete{{ forloop.counter }}" name="update" value="{{ item.id }}"><span class="glyphicon glyphicon-pencil"/></button>{% endif %}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </form>
                    {% else %}
                    <h2>You don't have any items</h2>
                    {% endif %}
                    <hr>
                </div>

            </div>
        </div>
{% endblock %}

inventory/templates/inventory/update.html
<style  type="text/css" rel="stylesheet">
    .color1{
        font-weight: 600;
        color: #13a1a5 !important;
    }

    .sman-footer-main{
        position: fixed;
        bottom: 0px;
        height: 30px;
        display: inline;
        width: 100%;
        color: #13a1a5;
        padding-right: 30px;
        padding-left: 30px;
        background-color: white;
    }
    .float-left{
        float: left;
    }
    .float-right{
        float: right;
    }
    text-center{
        text-align: center;
    }
    inline-block{
        display: inline;
    }

    /*  Button Style */

    .btn-outline-primary{
        border-color: #13a1a5;
        border-style: solid;
        border-width: 5px;
    }
    .sman-btn{
        background-color: white;
        border-style: solid;
        border-radius: 5px;
        border-color: #13a1a5;
        color: #13a1a5;
        padding-top: 7px;
        padding-bottom: 7px;
        padding-left: 15px;
        padding-right: 15px;
        min-width: 150px;
        font-weight: 600;
        font-size: 15px;
    }
    .sman-input-login
    {
        margin-right: 50px;
        color: #13a1a5;
        font-weight: 600;
        border-style: solid;
        border-radius: 2px;
        min-height: 30px;
        min-width: 200px;
        border-color: #13a1a5;

    }
    .sman-btn-main
    {
        margin-top: 100px;
    }

    .sman-content-main{
        padding-bottom: 10px;
        padding-top: 10px;
        font-weight: 600;
        font-size: 15px;
        margin-top: 100px;
        background-color: white;
        color:#13a1a5;

    }
    .sman-body-margin{
        margin-top: 100px;
        margin-bottom: 100px;
    }
    .font-weight-list
    {
        font-weight: 600 !important;
    }
    .font-glyphy
    {
        font-size: 20px;
    }
    .fa{
        margin-left: 40px;
    }
    .footer-copyright{
        padding-top: 10px;
    }
    @media only screen and (max-width: 600px) {
        .sman-body{
            padding: 0 !important;
        }
    }
    .color-white{
        color: white;
    }
    .sman-form-header{
        font-weight: 600;
        font-size: 20px;
        width: 100%;
        background-color: #13a1a5 !important;
    }
    .sman-login-context{
        margin-top: 100px;
        margin-bottom: 100px;

    }
    .sman-row{
        padding: 0;
    }
    .sman-container{
        padding: 0;
        background-color: black;
    }
    div.sman-inline{
        display: inline-block;
    }
    .sman-align-left{
        text-align: left;
    }
    .sman-align-center{
        text-align: center;
    }
    .sman-btn-container{
        margin-top: 20px;
    }
    .sman-radio-label{
        margin-right: 50px;
        color: #13a1a5;
        font-weight: 600;
        font-size: 15px;
    }
    .sman-color-warning{
        color: red;
    }
    .table-item{
        padding-right: 20px;
        margin-bottom: 20px;
    }
</style>
{% extends 'inventory/base.html' %}
{% block navblock %}
<li><a class="color1" href="{% url 'account:logout' %}">LOGOUT</a></li>
{% endblock %}
{% block sideblock%}
<div class="sman-sidebar-item">
    <a href="{% url 'account:slave_signup' %}">Add User</a>
</div>
{% endblock %}
{% block body %}
<div class="col-md-9 text-center">
            <div class="row">
                <div class="sman-form-header">
                    <font class="color-white">Update Item</font>
                </div>
                <div class="sman-login-context">
                    <div class="sman-inline sman-align-left">
                        <br>
                        <hr>
                        <table>
                        <form action="{% url 'inventory:update-inventory' %}" method="post">
                            {% csrf_token %}
                            <tr style="display: none;">
                                <td><label class="table-item sman-color-warning">Id</label></td>
                                <td><label class="table-item">{{ item_id }}</label></td>
                                <td><label class="table-item sman-color-warning">to</label></td>
                                <td><input class="table-item sman-input-login" name="item_id" type="text" value="{{ item_id }}" required></td>
                            </tr>
                            <tr>
                                <td><label class="table-item sman-color-warning">Update</label></td>
                                <td><label class="table-item">{{ item_name }}</label></td>
                                <td><label class="table-item sman-color-warning">to</label></td>
                                <td><input class="table-item sman-input-login" name="item_name" type="text" placeholder="Enter Item Name" required></td>
                            </tr>
                            <tr>
                                <td><label class="table-item sman-color-warning">Update</label></td>
                                <td><label class="table-item">{{ item_qty }}</label></td>
                                <td><label class="table-item sman-color-warning">to</label></td>
                                <td><input class="table-item sman-input-login" name="item_qty" type="text" placeholder="Enter Quantity" required></td>
                            </tr>
                            <tr>
                                <td><label class="table-item sman-color-warning">Update</label></td>
                                <td><label class="table-item">{{ item_price }}</label></td>
                                <td><label class="table-item sman-color-warning">to</label></td>
                                <td><input class="table-item sman-input-login" name="item_price" type="text" placeholder="Enter Price" required></td>
                            </tr>
                            <tr>
                                <td colspan="4">
                                    <div class="sman-align-center sman-btn-container">
                                        <input class="sman-btn btn-outline-primary" type="Submit" name="update" value="UPDATE"/>
                                    </div>
                                </td>
                            </tr>
                        </form>
                        </table>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}